language: node_js
node_js:
  - "6.1"
cache:
  timeout: 3600
  directories:
    - node_modules
    - bower_components
install:
  - npm install -g bower
  - npm install -g polymer-cli
before_script:
  - bower install
script:
  - polymer build
deploy:
  provider: firebase
  skip_cleanup: true
  edge:
    source: jorgecasar/dpl
    branch: fix/503-firebase-deploy-project-option
  token: "${FIREBASE_TOKEN}"
  project: "${FIREBASE_PROJECT_ID}"
  on:
    branch: master
